###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '8889:8025'

    mariadb:
        image: 'mariadb:10.6'
        working_dir: /application
        volumes:
            - '.:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=forge
            - MYSQL_DATABASE=forge
            - MYSQL_USER=forge
            - MYSQL_PASSWORD=forge
        ports:
            - '8891:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '../docker/src:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8888:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - '../docker/src:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
